/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author katarina
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna2
     */
    public FrmGlavna() {
        initComponents();
    }

    FrmGlavna(JLabel lblZaposleni) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Prodavnica gramofonskih ploča - klijentska aplikacija");
        lblPoruka.setText("Zaposleni koji je trenutno ulogovan na sistem: " + lblZaposleni.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPoruka = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKupac = new javax.swing.JMenu();
        miUnosKupca = new javax.swing.JMenuItem();
        miAzuriranjeKupca = new javax.swing.JMenuItem();
        menuPloca = new javax.swing.JMenu();
        miUnosPloce = new javax.swing.JMenuItem();
        miAzuriranjePloce = new javax.swing.JMenuItem();
        menuRacun = new javax.swing.JMenu();
        miUnosRacuna = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPoruka.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        lblPoruka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoruka.setText("jLabel1");

        menuKupac.setText("Kupci        ");
        menuKupac.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        miUnosKupca.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        miUnosKupca.setText("Unos kupca");
        miUnosKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosKupcaActionPerformed(evt);
            }
        });
        menuKupac.add(miUnosKupca);

        miAzuriranjeKupca.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        miAzuriranjeKupca.setText("Ažuriranje kupca");
        miAzuriranjeKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAzuriranjeKupcaActionPerformed(evt);
            }
        });
        menuKupac.add(miAzuriranjeKupca);

        jMenuBar1.add(menuKupac);

        menuPloca.setText("Gramofonske ploče         ");
        menuPloca.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        miUnosPloce.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        miUnosPloce.setText("Unos gramofonske ploče");
        miUnosPloce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosPloceActionPerformed(evt);
            }
        });
        menuPloca.add(miUnosPloce);

        miAzuriranjePloce.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        miAzuriranjePloce.setText("Ažuriranje gramofonske ploče");
        miAzuriranjePloce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAzuriranjePloceActionPerformed(evt);
            }
        });
        menuPloca.add(miAzuriranjePloce);

        jMenuBar1.add(menuPloca);

        menuRacun.setText("Račun");
        menuRacun.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        miUnosRacuna.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        miUnosRacuna.setText("Unos računa");
        miUnosRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosRacunaActionPerformed(evt);
            }
        });
        menuRacun.add(miUnosRacuna);

        jMenuBar1.add(menuRacun);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPoruka, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lblPoruka)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUnosKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosKupcaActionPerformed
        PnlUnosKupca unosKupca = new PnlUnosKupca();
        JDialog dialog = new JDialog(this, "Prodavnica gramofonskih ploča - unos kupca", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(unosKupca);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_miUnosKupcaActionPerformed

    private void miAzuriranjeKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAzuriranjeKupcaActionPerformed
        PnlPretragaKupaca pretragaKupaca = new PnlPretragaKupaca();
        JDialog dialog = new JDialog(this, "Prodavnica gramofonskih ploča - pretraga kupaca", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(pretragaKupaca);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_miAzuriranjeKupcaActionPerformed

    private void miUnosPloceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosPloceActionPerformed
        PnlUnosPloce unosPloce = new PnlUnosPloce();
        JDialog dialog = new JDialog(this, "Prodavnica gramofonskih ploča - unos gramofonske ploče", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(unosPloce);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_miUnosPloceActionPerformed

    private void miAzuriranjePloceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAzuriranjePloceActionPerformed
        PnlPretragaPloca pretragaPloca = new PnlPretragaPloca();
        JDialog dialog = new JDialog(this, "Prodavnica gramofonskih ploča - pretraga ploča", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(pretragaPloca);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_miAzuriranjePloceActionPerformed

    private void miUnosRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosRacunaActionPerformed
        PnlUnosRacuna unosRacuna = new PnlUnosRacuna();
        JDialog dialog = new JDialog(this, "Prodavnica gramofonskih ploča - unos računa", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(unosRacuna);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_miUnosRacunaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JMenu menuKupac;
    private javax.swing.JMenu menuPloca;
    private javax.swing.JMenu menuRacun;
    private javax.swing.JMenuItem miAzuriranjeKupca;
    private javax.swing.JMenuItem miAzuriranjePloce;
    private javax.swing.JMenuItem miUnosKupca;
    private javax.swing.JMenuItem miUnosPloce;
    private javax.swing.JMenuItem miUnosRacuna;
    // End of variables declaration//GEN-END:variables
}
