/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.Ploca;
import domen.Racun;
import domen.StavkaRacuna;
import gui.stavkaracuna.kki.UnosStavkeRacunaKKI;
import java.awt.Font;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author katarina
 */
public class PnlUnosStavkeRacuna extends javax.swing.JPanel {

    PnlUnosRacuna panel;
    List<StavkaRacuna> listaStavkiRacuna;
    Racun racun;

    /**
     * Creates new form PnlUnosStavkeRacuna
     */
    public PnlUnosStavkeRacuna() {
        initComponents();
    }

    PnlUnosStavkeRacuna(PnlUnosRacuna panel, Racun racun) {
        this.panel = panel;
        this.racun = racun;
        listaStavkiRacuna = this.panel.getListaSstavkiRacuna();
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRedniBroj = new javax.swing.JTextField();
        btnVratiRedniBroj = new javax.swing.JButton();
        btnSacuvajStavkuRacuna = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        cbPloca = new javax.swing.JComboBox<>();
        txtKolicina = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setText("Redni broj:");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel2.setText("Ploča:");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel3.setText("Količina:");

        txtRedniBroj.setEditable(false);
        txtRedniBroj.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtRedniBroj.setEnabled(false);

        btnVratiRedniBroj.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnVratiRedniBroj.setText("Vrati redni broj");
        btnVratiRedniBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiRedniBrojActionPerformed(evt);
            }
        });

        btnSacuvajStavkuRacuna.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnSacuvajStavkuRacuna.setText("Sačuvaj stavku računa");
        btnSacuvajStavkuRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajStavkuRacunaActionPerformed(evt);
            }
        });

        btnOdustani.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        cbPloca.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        cbPloca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtKolicina.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacuvajStavkuRacuna)
                        .addGap(18, 18, 18)
                        .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRedniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVratiRedniBroj))
                    .addComponent(cbPloca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKolicina))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRedniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVratiRedniBroj))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPloca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajStavkuRacuna)
                    .addComponent(btnOdustani))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVratiRedniBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiRedniBrojActionPerformed
        int redniBroj = UnosStavkeRacunaKKI.vratiRedniBroj(listaStavkiRacuna, txtRedniBroj);

        if (redniBroj <= 0) {
            JLabel label = new JLabel("Sistem ne može da kreira novu stavku računa!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, label, "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JLabel label = new JLabel("Sistem je kreirao novu stavku računa!");
        label.setFont(new Font("Calibri light", Font.PLAIN, 16));
        JOptionPane.showMessageDialog(this, label);
        btnVratiRedniBroj.setEnabled(false);
        txtKolicina.setText("1");
        txtKolicina.grabFocus();
        txtKolicina.setSelectionStart(0);
    }//GEN-LAST:event_btnVratiRedniBrojActionPerformed

    private void btnSacuvajStavkuRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajStavkuRacunaActionPerformed
        if (txtRedniBroj.getText().isEmpty()) {
            JLabel label = new JLabel("Morate generisati redni broj stavke!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, label, "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtKolicina.getText().isEmpty()) {
            JLabel label = new JLabel("Morate uneti količinu ploča!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, label, "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Integer.parseInt(txtKolicina.getText()) == 0) {
            JLabel label = new JLabel("Količina ne može biti 0!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, label, "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<Ploca> lps = new ArrayList<>();
        Ploca p = (Ploca) cbPloca.getSelectedItem();
        for (StavkaRacuna stavkaRacuna : listaStavkiRacuna) {
            lps.add(stavkaRacuna.getPloca());

            if (lps.contains(p)) {
                int kolicina = Integer.valueOf(txtKolicina.getText());
                stavkaRacuna.setKolicina(stavkaRacuna.getKolicina() + kolicina);
                panel.izmeniTabelu(p, kolicina);
                JLabel label = new JLabel("Ta ploča već postoji, izmeniće se samo količina!");
                label.setFont(new Font("Calibri light", Font.PLAIN, 16));
                JOptionPane.showMessageDialog(null, label);
                JComponent comp = (JComponent) evt.getSource();
                Window win = SwingUtilities.getWindowAncestor(comp);
                win.dispose();
                return;
            }
        }

        StavkaRacuna stavkaRacuna = UnosStavkeRacunaKKI.sacuvajStavkuRacuna(racun, txtRedniBroj, cbPloca, txtKolicina, listaStavkiRacuna);
        panel.dodajUTabelu(stavkaRacuna);

        panel.dodajIznos(stavkaRacuna.getIznos());
//        srediFormu();
        JComponent comp = (JComponent) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor(comp);
        win.dispose();
    }//GEN-LAST:event_btnSacuvajStavkuRacunaActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        JComponent comp = (JComponent) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor(comp);
        win.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSacuvajStavkuRacuna;
    private javax.swing.JButton btnVratiRedniBroj;
    private javax.swing.JComboBox<Object> cbPloca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtRedniBroj;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        UnosStavkeRacunaKKI.vratiPloce(cbPloca);
        txtRedniBroj.setText("");
        txtKolicina.setText("");
        btnVratiRedniBroj.setEnabled(true);
    }
}
