/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.Ploca;
import domen.Racun;
import domen.StavkaRacuna;
import domen.Zaposleni;
import gui.prijava.kki.PrijavaKKI;
import gui.racun.kki.UnosRacunaKKI;
import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.Font;
import java.awt.Window;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.JTableHeader;
import model.TableModelStavkaRacuna;

/**
 *
 * @author katarina
 */
public class PnlUnosRacuna extends javax.swing.JPanel {

    List<StavkaRacuna> listaStavkiRacuna;
    double ukupanIznos = 0;
    Zaposleni prijavljeni;
    Racun racun;

    /**
     * Creates new form PnlUnosRacuna
     */
    public PnlUnosRacuna() {
        initComponents();
        listaStavkiRacuna = new ArrayList<>();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkaRacuna = new javax.swing.JTable();
        txtRacunID = new javax.swing.JTextField();
        cbKupac = new javax.swing.JComboBox<>();
        txtDatum = new javax.swing.JTextField();
        btnKreirajNoviRacun = new javax.swing.JButton();
        btnDodajStavkuRacuna = new javax.swing.JButton();
        btnObrisiStavkuRacuna = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        btnSacuvajRacun = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setText("Račun ID:");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel2.setText("Datum:");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel3.setText("Kupac:");

        tblStavkaRacuna.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        tblStavkaRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkaRacuna);

        txtRacunID.setEditable(false);
        txtRacunID.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtRacunID.setEnabled(false);

        cbKupac.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        cbKupac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDatum.setEditable(false);
        txtDatum.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        btnKreirajNoviRacun.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnKreirajNoviRacun.setText("Kreiraj novi račun");
        btnKreirajNoviRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajNoviRacunActionPerformed(evt);
            }
        });

        btnDodajStavkuRacuna.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnDodajStavkuRacuna.setText("Dodaj stavku računa");
        btnDodajStavkuRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuRacunaActionPerformed(evt);
            }
        });

        btnObrisiStavkuRacuna.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnObrisiStavkuRacuna.setText("Obriši stavku računa");
        btnObrisiStavkuRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuRacunaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel4.setText("Ukupan iznos:");

        txtUkupanIznos.setEditable(false);
        txtUkupanIznos.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtUkupanIznos.setEnabled(false);

        btnSacuvajRacun.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnSacuvajRacun.setText("Sačuvaj račun");
        btnSacuvajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajRacunActionPerformed(evt);
            }
        });

        btnOdustani.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatum)
                            .addComponent(cbKupac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRacunID)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtUkupanIznos)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisiStavkuRacuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDodajStavkuRacuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKreirajNoviRacun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacuvajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtRacunID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKreirajNoviRacun))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnDodajStavkuRacuna)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiStavkuRacuna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvajRacun)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOdustani))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajNoviRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajNoviRacunActionPerformed
        int racunID = UnosRacunaKKI.vratiID(txtRacunID);
        if (racunID <= 0) {
            JLabel label = new JLabel("Sistem ne može da kreira novi račun!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, label, "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JLabel label = new JLabel("Sistem je kreirao novi račun!");
        label.setFont(new Font("Calibri light", Font.PLAIN, 16));
        JOptionPane.showMessageDialog(this, label);
        btnKreirajNoviRacun.setEnabled(false);
        postaviDatum();
    }//GEN-LAST:event_btnKreirajNoviRacunActionPerformed

    private void btnDodajStavkuRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuRacunaActionPerformed
        if (txtRacunID.getText().isEmpty()) {
            JLabel label = new JLabel("Morate kreirati račun da biste dodali stavku!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, label, "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        racun = new Racun();
        racun.setRacunID(Integer.parseInt(txtRacunID.getText()));

        PnlUnosStavkeRacuna unosStavkeRacuna = new PnlUnosStavkeRacuna(this, racun);
        JDialog dialog = new JDialog((Dialog) SwingUtilities.getWindowAncestor(this), "Prodavnica gramofonskih ploča - unos stavke računa", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(unosStavkeRacuna);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnDodajStavkuRacunaActionPerformed

    private void btnObrisiStavkuRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuRacunaActionPerformed
        if (tblStavkaRacuna.getSelectedRow() < 0) {
            JLabel label = new JLabel("Morate odabrati stavku koju želite da obrišete!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, label, "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int selektovanRed = tblStavkaRacuna.getSelectedRow();
        TableModelStavkaRacuna tmsr = (TableModelStavkaRacuna) tblStavkaRacuna.getModel();
        StavkaRacuna stavka = tmsr.vratiStavkuRacuna(selektovanRed);
        tmsr.obrisiStavku(selektovanRed);
        ukupanIznos = ukupanIznos - stavka.getIznos();
        txtUkupanIznos.setText(String.valueOf(ukupanIznos));
    }//GEN-LAST:event_btnObrisiStavkuRacunaActionPerformed

    private void btnSacuvajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajRacunActionPerformed
        TableModelStavkaRacuna tmsr = (TableModelStavkaRacuna) tblStavkaRacuna.getModel();
        List<StavkaRacuna> listaStavkiRacuna = tmsr.getListaStavkiRacuna();

        if (listaStavkiRacuna.isEmpty()) {
            JLabel label = new JLabel("Račun mora imati bar jednu stavku!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, label, "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean uspesno = UnosRacunaKKI.sacuvajRacun(txtRacunID, cbKupac, txtDatum, txtUkupanIznos, listaStavkiRacuna);
        if (uspesno) {
            JLabel label = new JLabel("Sistem je uspešno sačuvao račun!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(this, label);
            resetuj();
        } else {
            JLabel label = new JLabel("Sistem ne može da zapamti račun!");
            label.setFont(new Font("Calibri light", Font.PLAIN, 16));
            JOptionPane.showMessageDialog(null, label, "Greška!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajRacunActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        JComponent comp = (JComponent) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor(comp);
        win.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavkuRacuna;
    private javax.swing.JButton btnKreirajNoviRacun;
    private javax.swing.JButton btnObrisiStavkuRacuna;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSacuvajRacun;
    private javax.swing.JComboBox<Object> cbKupac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStavkaRacuna;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtRacunID;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        TableModelStavkaRacuna tmsr = new TableModelStavkaRacuna(listaStavkiRacuna);
        tblStavkaRacuna.setModel(tmsr);

        UnosRacunaKKI.vratiKupce(cbKupac);
        prijavljeni = PrijavaKKI.prijavljeni;

        txtUkupanIznos.setText(String.valueOf(ukupanIznos));
        
        JTableHeader tblHeader = tblStavkaRacuna.getTableHeader();
        tblHeader.setFont(new Font("Calibri light", Font.PLAIN, 16));
    }

    public void dodajUTabelu(StavkaRacuna stavkaRacuna) {
        TableModelStavkaRacuna tmsr = (TableModelStavkaRacuna) tblStavkaRacuna.getModel();
        tmsr.dodajStavku(stavkaRacuna);
    }

    List<StavkaRacuna> getListaSstavkiRacuna() {
        TableModelStavkaRacuna tmsr = (TableModelStavkaRacuna) tblStavkaRacuna.getModel();
        return tmsr.getListaStavkiRacuna();
    }

    public void setListaStavkiRacuna(List<StavkaRacuna> listaStavkiRacuna) {
        this.listaStavkiRacuna = listaStavkiRacuna;
    }

    void dodajIznos(double iznos) {
        ukupanIznos = ukupanIznos + iznos;
        txtUkupanIznos.setText(String.valueOf(ukupanIznos));
    }

    private void postaviDatum() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        String datum = sdf.format(new Date());
        txtDatum.setText(datum);
    }

    private void resetuj() {
        txtRacunID.setText("");
        txtDatum.setText("");
        txtUkupanIznos.setText("");
        ukupanIznos = 0;
        setListaStavkiRacuna(new ArrayList<>());
        TableModelStavkaRacuna tmsr = (TableModelStavkaRacuna) tblStavkaRacuna.getModel();
        tmsr.setListaStavkiRacuna(listaStavkiRacuna);
        tmsr.fireTableDataChanged();
        UnosRacunaKKI.vratiKupce(cbKupac);

        btnKreirajNoviRacun.setEnabled(true);

    }

    void izmeniTabelu(Ploca ploca, int kolicina) {
        TableModelStavkaRacuna tmrs = (TableModelStavkaRacuna) tblStavkaRacuna.getModel();
        listaStavkiRacuna = tmrs.getListaStavkiRacuna();
        for (StavkaRacuna stavkaRacuna : listaStavkiRacuna) {
            if (stavkaRacuna.getPloca().equals(ploca)) {
                System.out.println(stavkaRacuna.getPloca() + " = " + ploca );
                stavkaRacuna.setKolicina(stavkaRacuna.getKolicina() + kolicina);
                tmrs.setListaStavkiRacuna(listaStavkiRacuna);
            }
        }
    }
}
